# Generated by Django 4.2.30 on 2026-05-22 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartOfAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(blank=True, max_length=100)),
                ('account_name', models.CharField(max_length=200)),
                ('account_code', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('account_type', models.CharField(blank=True, max_length=100)),
                ('account_status', models.CharField(blank=True, max_length=20)),
                ('currency', models.CharField(blank=True, max_length=10)),
                ('parent_account', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['account_type', 'account_name'],
            },
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField(blank=True, null=True)),
                ('transaction_type', models.CharField(blank=True, max_length=100)),
                ('from_account', models.CharField(blank=True, max_length=200)),
                ('to_account', models.CharField(blank=True, max_length=200)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('payment_mode', models.CharField(blank=True, max_length=50)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal_number', models.CharField(blank=True, max_length=50)),
                ('zoho_journal_id', models.CharField(blank=True, max_length=100)),
                ('journal_date', models.DateField(blank=True, null=True)),
                ('journal_type', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(blank=True, max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_by', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-journal_date'],
            },
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True)),
                ('zoho_order_id', models.CharField(blank=True, max_length=100)),
                ('customer_name', models.CharField(blank=True, max_length=200)),
                ('order_date', models.DateField(blank=True, null=True)),
                ('expected_shipment_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=30)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('salesperson', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-order_date'],
            },
        ),
    ]
