# Generated by Django 4.2.30 on 2026-05-19 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('product_status_changed', 'Product Status Changed'), ('product_reserved', 'Product Reserved'), ('reservation_cancelled', 'Reservation Cancelled'), ('product_sold', 'Product Sold'), ('quotation_created', 'Quotation Created'), ('invoice_created', 'Invoice Created in Zoho'), ('customer_updated', 'Customer Updated'), ('lead_stage_changed', 'Lead Stage Changed'), ('after_sales_status_changed', 'After Sales Status Changed'), ('sync_failed', 'Sync Failed'), ('sync_retried', 'Sync Retried'), ('user_login', 'User Login'), ('csv_import', 'CSV Import')], max_length=50)),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_id', models.CharField(max_length=100)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
