# Generated by Django 4.2.30 on 2026-05-19 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AfterSalesRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_reference', models.CharField(blank=True, max_length=100)),
                ('request_type', models.CharField(choices=[('resize', 'Resize'), ('repair', 'Repair'), ('polish', 'Polish'), ('stone_replacement', 'Stone Replacement'), ('certificate_issue', 'Certificate Issue'), ('exchange', 'Exchange'), ('return', 'Return'), ('cleaning', 'Cleaning'), ('custom_modification', 'Custom Modification')], max_length=30)),
                ('received_date', models.DateField()),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('delivered_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('received', 'Received'), ('inspection', 'Inspection'), ('in_progress', 'In Progress'), ('ready', 'Ready'), ('delivered', 'Delivered'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='received', max_length=20)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_service', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_service_requests', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='after_sales_requests', to='customers.customer')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='after_sales_requests', to='products.product')),
            ],
            options={
                'verbose_name': 'After Sales Request',
                'verbose_name_plural': 'After Sales Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AfterSalesImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_type', models.CharField(choices=[('before', 'Before'), ('after', 'After')], max_length=10)),
                ('file_url', models.TextField()),
                ('file_name', models.CharField(max_length=255)),
                ('gcs_path', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('after_sales_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='after_sales.aftersalesrequest')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'After Sales Image',
                'verbose_name_plural': 'After Sales Images',
            },
        ),
    ]
