# Generated by Django 4.2.30 on 2026-05-22 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['stage'], name='leads_lead_stage_4b0a5d_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['follow_up_date'], name='leads_lead_follow__064bf5_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['assigned_to'], name='leads_lead_assigne_3f8857_idx'),
        ),
    ]
