# Generated by Django 4.2.30 on 2026-05-19 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zoho_contact_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('mobile', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('customer_type', models.CharField(choices=[('retail', 'Retail'), ('wholesale', 'Wholesale'), ('vip', 'VIP')], default='retail', max_length=20)),
                ('lead_source', models.CharField(blank=True, choices=[('walk_in', 'Walk In'), ('referral', 'Referral'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('website', 'Website'), ('exhibition', 'Exhibition'), ('other', 'Other')], max_length=30)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('anniversary', models.DateField(blank=True, null=True)),
                ('preferred_category', models.CharField(blank=True, max_length=100)),
                ('preferred_metal', models.CharField(blank=True, choices=[('gold_14k', '14K Gold'), ('gold_18k', '18K Gold'), ('gold_22k', '22K Gold'), ('platinum', 'Platinum'), ('silver', 'Silver')], max_length=30)),
                ('preferred_budget_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('preferred_budget_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('ring_size', models.CharField(blank=True, max_length=10)),
                ('bracelet_size', models.CharField(blank=True, max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_customers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['-created_at'],
            },
        ),
    ]
