# Generated by Django 4.2.30 on 2026-05-22 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('quotations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='customers.customer'),
        ),
    ]
