# Generated by Django 4.2.30 on 2026-05-22 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0002_alter_quotation_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='attached_image',
            field=models.ImageField(blank=True, null=True, upload_to='quotations/'),
        ),
    ]
