# Generated by Django 4.2.30 on 2026-05-19 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('file_path', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total_rows', models.IntegerField(default=0)),
                ('imported_rows', models.IntegerField(default=0)),
                ('skipped_rows', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('missing_sku_count', models.IntegerField(default=0)),
                ('duplicate_sku_count', models.IntegerField(default=0)),
                ('missing_cert_count', models.IntegerField(default=0)),
                ('invalid_price_count', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_detail', models.JSONField(default=list)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Import Log',
                'verbose_name_plural': 'Import Logs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zoho_item_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('item_name', models.CharField(max_length=500)),
                ('sku', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('rings', 'Rings'), ('solitaire_rings', 'Solitaire Rings'), ('small_earrings', 'Small Earrings'), ('cocktail_earrings', 'Cocktail Earrings'), ('solitaire_earrings', 'Solitaire Earrings'), ('bracelets', 'Bracelets'), ('bangles', 'Bangles'), ('necklaces', 'Necklaces'), ('pendants', 'Pendants'), ('chains', 'Chains'), ('pendant_chain', 'Pendant Chain'), ('nose_pins', 'Nose Pins'), ('ear_cuffs', 'Ear Cuffs'), ('packaging', 'Packaging Material'), ('other', 'Other')], default='other', max_length=30)),
                ('subcategory', models.CharField(blank=True, max_length=100)),
                ('selling_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('gross_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('net_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('diamond_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('metal_type', models.CharField(blank=True, choices=[('gold', 'Gold'), ('platinum', 'Platinum'), ('silver', 'Silver')], max_length=20)),
                ('metal_purity', models.CharField(blank=True, choices=[('14k', '14K'), ('18k', '18K'), ('22k', '22K'), ('24k', '24K'), ('925', '925 Silver'), ('950', '950 Platinum')], max_length=10)),
                ('stone_type', models.CharField(blank=True, max_length=100)),
                ('certification_type', models.CharField(choices=[('none', 'No Certificate'), ('generic', 'Yes - Generic'), ('igi', 'IGI'), ('sgl', 'SGL'), ('hallmark', 'Hallmark'), ('unknown', 'Unknown')], default='none', max_length=20)),
                ('certification_number', models.CharField(blank=True, max_length=100)),
                ('inventory_status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('sold', 'Sold'), ('returned', 'Returned'), ('under_service', 'Under Service'), ('archived', 'Archived')], default='available', max_length=20)),
                ('zoho_status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=20)),
                ('date_of_purchase', models.DateField(blank=True, null=True)),
                ('hsn_code', models.CharField(blank=True, max_length=20)),
                ('making_charges', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.TextField()),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=50)),
                ('is_primary', models.BooleanField(default=False)),
                ('gcs_path', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Product Images',
            },
        ),
        migrations.CreateModel(
            name='ProductCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_type', models.CharField(max_length=20)),
                ('certificate_number', models.CharField(blank=True, max_length=100)),
                ('file_url', models.TextField()),
                ('file_name', models.CharField(max_length=255)),
                ('gcs_path', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='products.product')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product Certificate',
                'verbose_name_plural': 'Product Certificates',
            },
        ),
        migrations.CreateModel(
            name='ImportLogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField()),
                ('sku', models.CharField(blank=True, max_length=100)),
                ('item_name', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('import_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.importlog')),
            ],
            options={
                'verbose_name': 'Import Log Item',
                'verbose_name_plural': 'Import Log Items',
                'ordering': ['row_number'],
            },
        ),
    ]
